### ISSUE TITLE
Avoid jumping between bash and R

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/pactaCore#26]
Right now we jump a lot bwtween bash and R. For example
we use ./bin/run-pacta and `R/run_pacta()`.

It would be nice to do all in one place.

I prefer to work in R mostly because that let us 1) test with
testthat and 2) develop interactively, both in normal and 
debugger mode.

@jdhoffa, I know you prefer to stay in the shell. Can you 
comment on why?

**Comment by jdhoffa** [comment]
I guess it is not a very strong preference, but I'll try to explain below:
Essentially, I feel like it would be good to separate (as much as possible) the core tooling of PACTA (that achieves the target calculations, groupings, etc.) from the implementation details (file management, etc.)

My initial desire was to make that separation with just R and a Dockerfile, where docker would handle all the implementation details, and R could be used exclusively for PACTA tools. 

At some point, we extracted some of the Docker details into bash scripts, to simplify the Dockerfile and now we seem to be extracting those bash scripts back into R. 

In the spirit of getting this work package ready, I'm not a fan of the idea of having things like `../input` and `../output` in the core R functions. I really imagined the setup as follows: 

1. R functions provide the core tooling of PACTA, which can be called in different orders, with different arguments. **Language:** this would be written in `R` and ideally eventually an R package.
2. Different scripts are defined by calling these functions in a certain way (with certain arguments etc.). **Language:** I don't see this being written in an R file, I would see this served better as an `.Rmd`.
3. We wrap these workflows in a very stable environment (computing environment, dependencies, and file management all handled), and the user can spin this up in docker. **Language:** I would hope to write this as a `Dockerfile` as much as possible, extracting parts into bash scripts when necessary. 

 But, this is just my preference, and I could be wrong.

**Comment by jdhoffa** [comment]
I think the preference also comes from eventually seeing the PACTA part removed entirely and published as a package. If all that is in the `R/` folder is directly related to PACTA tools, then we can easily remove it, and we could have a repo called "workflows" or something that just calls those tools in different ways. If we start combining everything into R, it's going to be much more difficult to mentally visualize what each part of the repo is actually hoping to achieve.
