### ISSUE TITLE
Test test test before refactoring the pacta code

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/pactaCore#27]
So far we've been careful to not change anything in the pacta
source code. But we will soon as we no longer have ties with
PACTA_analysis and plan to build an R package. Before that
we need a regression test. 

Maybe we can snapshot the tree of ../output after calling
`run_pacta()`. We could do this locally or in GH Actions.

**Comment by jdhoffa** [comment]
I think that our first test should be a very brittle regression test. 
We should use as input the files (these are copied into the `input` directory): 
* `./working_dir/10_Parameter_File/TestPortfolio_Input_PortfolioParameters.yml`
* `./working_dir/20_Raw_Inputs/TestPortfolio_Input.csv`

We should test against snapshots of the contents of: 
 * `output/working_dir/40_Results/TestPortfolio_Input/`
Ideally, we test all 6 files in that folder. But the files: `Bonds_results_company.rda` and `Equity_results_company.rda` contain the most granular information and would be a good starting point for tests.

**Comment by jdhoffa** [comment]
Relates to #55
